import re
from math import isfinite

from pydantic import BaseModel, ConfigDict, Field, field_validator


def product_query_key(value: str) -> str:
    return value.strip().casefold()


class SupplierProfile(BaseModel):
    """Operator-supplied identity and price; never generated by the model."""
    model_config = ConfigDict(extra="forbid", frozen=True)
    supplier_key: str = Field(pattern=r"^[A-Za-z0-9_-]{1,64}$")
    name: str = Field(min_length=1)
    email: str = Field(min_length=3)
    unit_price: float = Field(gt=0, allow_inf_nan=False)

    @field_validator("name")
    @classmethod
    def valid_name(cls, value):
        value = value.strip()
        if not value or any(ord(c) < 32 for c in value):
            raise ValueError("Supplier name must be nonempty plain text.")
        return value

    @field_validator("email")
    @classmethod
    def valid_email(cls, value):
        value = value.strip().lower()
        if not re.fullmatch(r"[^\s@]+@[^\s@]+\.[^\s@]+", value):
            raise ValueError("Supply a plain supplier email address.")
        return value

    @field_validator("unit_price", mode="before")
    @classmethod
    def valid_price(cls, value):
        if isinstance(value, bool) or not isinstance(value, (int, float)) or not isfinite(value) or value <= 0:
            raise ValueError("Supplier unit_price must be a finite positive number.")
        return value
